### ISSUE TITLE
Errors for jpg uploads

### ISSUE THREAD

**Issue by leetiszenkel** [aerouk/imageserve#16]
I have everything up and running fine, png and gif uploads go without a hitch, but jpg uploads have been acting weird. First I was getting e-503 for jpgs, despite all permissions being fine. I renamed the image/jpeg folder to image/jpg and they upload successfully now but result in a 404 when trying to view.

Tried replacing my upload.php with the replacement from addles' earlier issue, both with the folder name image/jpeg and image/jpg, and received the same results.

**Comment by aerouk** [comment]
I did figure out a fix for this but I haven't uploaded it yet. I'll get on this later.

**Comment by aerouk** [comment]
Update to this: I found a pretty glaring error, fixing it right now.

**Comment by aerouk** [comment]
Fixed with commits:
- 7478986a8aedaf51289b00b863841232591f9161
- 42a5216ec6a58d78a326e95718f33337704d7cf0
- d707464c6ebbba60edf15eefb275bb3731654711
- 6af2ee6e3ef05f24f0900ae9a88ab35eb720108b
- e599989882eb0516b8430f8672b5a1a5e3069d9c
- a49478b1c534d736cefa7a9897a8f72d4f2230ef

Pushed to release https://github.com/aerouk/imageserve/releases/tag/0.0.3-prototype
