### ISSUE TITLE
Getting e-500x even after doing chmod 777

### ISSUE THREAD

**Issue by asianboiFRC** [aerouk/imageserve#22]
I am still getting an e-500x error, even after setting the permissions. Could SSH keys have something to do with it?

**Comment by aerouk** [comment]
Are you sure the permissions are set recursively? SSH keys should have no bearing here.

**Comment by mikexcao** [comment]
Yeah, I tried everything, including making the entire www/ directory writable.

**Comment by asianboiFRC** [comment]
![image](https://cloud.githubusercontent.com/assets/15696592/20281809/f5834250-aa7f-11e6-8703-92054dda0827.png)
I did that, and it still throws this:
![image](https://cloud.githubusercontent.com/assets/15696592/20281831/0e7d7488-aa80-11e6-9790-6e5c324b1943.png)

**Comment by aerouk** [comment]
Ensure you're using the `-R` flag with chmod to set the permissions recursively since you didn't actually do that in the screenshot above.

`$ chmod -R 777 images/`

**Comment by asianboiFRC** [comment]
![image](https://cloud.githubusercontent.com/assets/15696592/20291162/6bd2c714-aab2-11e6-8e3b-343148657998.png)

![image](https://cloud.githubusercontent.com/assets/15696592/20291170/7998a102-aab2-11e6-8f83-3161584abab6.png)

Still happens

**Comment by aerouk** [comment]
I still have no idea what could be going wrong here. Honestly, I'm running out of things to recommend, and I'm not one for providing tech support when it's out of scope for my project since this clearly isn't an issue on my end.

The only way you can get error 500x is if the file couldn't be moved from the apache temp directory to the target directory. Work from there.
