### ISSUE TITLE
Is there a way to stop this?

### ISSUE THREAD

**Issue by ApolloMason** [aerouk/imageserve#31]
I dont want my jpeg images going to a seperate folder, '/j/2kdl7' I want it to be like my PNG files, where it will only goto to the index page, for example 'https://theapollo.xyz/foLyQ'.

Is there a way to make the jpegs not go into the '/j' dir?

**Comment by addles** [comment]
Edit the upload.php and htaccess to make them all dump in the same folder

**Comment by ApolloMason** [comment]
I genuinely cant see anything that I can edit. Nor Idk what to add if I have to add shit. Both htaccess or upload.php

**Comment by ApolloMason** [comment]
What would I have to add/edit to make this possible?

**Comment by aerouk** [comment]
You'd have to edit upload.php to get the files to be moved to the same directory, change how files are checked so it checks the extension in the folder rather than the folder itself, and change how the program responds when a file is uploaded.

I don't really want to provide support for use cases outside of what is already provided so you can do this on your own from here.

**Comment by ApolloMason** [comment]
Can you atleast tell me if I need to add things.. Or just change shit.

**Comment by aerouk** [comment]
I told you what to change. Read what I posted.
