### ISSUE TITLE
Asks for enabling Javascript in Browser

### ISSUE THREAD

**Issue by Shatterproof81** [aerouk/imageserve#45]
@aerouk 
![image](https://user-images.githubusercontent.com/33436779/36348274-2bc5db28-143a-11e8-9bfc-846dd9ba1c2b.png)
Simply doesn't work, I followed all video instructions. My config is 

`<?php

//   _
//  (_)    A self-hosted ShareX image serving solution.
//   _ _ __ ___   __ _  __ _  ___  ___  ___ _ ____   _____
//  | | '_ ` _ \ / _` |/ _` |/ _ \/ __|/ _ \ '__\ \ / / _ \
//  | | | | | | | (_| | (_| |  __/\__ \  __/ |   \ V /  __/
//  |_|_| |_| |_|\__,_|\__, |\___||___/\___|_|    \_/ \___|
//                      __/ |
//                     |___/   created by github.com/aerouk

/* More information on all these values can be found on the wiki page. */
/* https://github.com/aerouk/imageserve/wiki/Configuration */

define('RAW_IMAGE', true);
define('RAW_IMAGE_LINK', false);
define('IMAGE_EXTENSION', false);

define('TWITTER_CARDS', false);

// If you're using this, make sure to put a forward slash before.
// E.g. "/imageserve" not "imageserve"
define('IMAGESERVE_DIR', '/images');
define('TWITTER_HANDLE', '');

define('APP_NAME', 'My App');
define('PASSKEY', 'removed');
`

**Comment by Shatterproof81** [comment]
It also leaves a 401

**Comment by aerouk** [comment]
None of imageserve uses any JavaScript, so I'm gonna say it's either down
to your web server setup itself or some intermediary such as cloudflare
blocking ShareX's request

On 18 Feb 2018 4:39 am, "Shatterproof81" <notifications@github.com> wrote:

It also leaves a 401

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/aerouk/imageserve/issues/45#issuecomment-366492171>,
or mute
the thread
